fix pre commit hooks

diff --git a/.husky/pre-push b/.husky/pre-push
--- a/.husky/pre-push
+++ b/.husky/pre-push
@@ -2,3 +2,11 @@
 . "$(dirname -- "$0")/_/husky.sh"
 
 npm run test
+RETVAL=$?
+if [ $RETVAL -ne 0 ]
+  then
+    echo "Grunt task failed, exiting..."
+    exit 1
+fi
+ 
+echo "Complete."
